# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_spatialmetrics.ui'
#
# Created: Wed Jan 22 11:08:57 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SpatialMetrics(object):
    def setupUi(self, SpatialMetrics):
        SpatialMetrics.setObjectName(_fromUtf8("SpatialMetrics"))
        SpatialMetrics.resize(529, 427)
        SpatialMetrics.setSizeGripEnabled(True)
        self.line_4 = QtGui.QFrame(SpatialMetrics)
        self.line_4.setGeometry(QtCore.QRect(480, 250, 20, 131))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_3 = QtGui.QFrame(SpatialMetrics)
        self.line_3.setGeometry(QtCore.QRect(20, 350, 471, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.btnBaseDir_3 = QtGui.QPushButton(SpatialMetrics)
        self.btnBaseDir_3.setGeometry(QtCore.QRect(450, 20, 47, 30))
        self.btnBaseDir_3.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/spatialmetrics/dir.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBaseDir_3.setIcon(icon)
        self.btnBaseDir_3.setIconSize(QtCore.QSize(22, 22))
        self.btnBaseDir_3.setObjectName(_fromUtf8("btnBaseDir_3"))
        self.label_19 = QtGui.QLabel(SpatialMetrics)
        self.label_19.setGeometry(QtCore.QRect(150, 260, 211, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_11 = QtGui.QLabel(SpatialMetrics)
        self.label_11.setGeometry(QtCore.QRect(30, 30, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.comboBox_3 = QtGui.QComboBox(SpatialMetrics)
        self.comboBox_3.setGeometry(QtCore.QRect(150, 120, 351, 31))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.line_5 = QtGui.QFrame(SpatialMetrics)
        self.line_5.setGeometry(QtCore.QRect(10, 250, 20, 131))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.label_17 = QtGui.QLabel(SpatialMetrics)
        self.label_17.setGeometry(QtCore.QRect(190, 180, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setTextFormat(QtCore.Qt.AutoText)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.pushButton_6 = QtGui.QPushButton(SpatialMetrics)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setGeometry(QtCore.QRect(290, 310, 121, 31))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.line = QtGui.QFrame(SpatialMetrics)
        self.line.setGeometry(QtCore.QRect(260, 280, 20, 81))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.buttonBox = QtGui.QDialogButtonBox(SpatialMetrics)
        self.buttonBox.setGeometry(QtCore.QRect(180, 200, 176, 27))
        self.buttonBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.comboBox_2 = QtGui.QComboBox(SpatialMetrics)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 70, 351, 31))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.label_15 = QtGui.QLabel(SpatialMetrics)
        self.label_15.setGeometry(QtCore.QRect(10, 80, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.line_18 = QtGui.QFrame(SpatialMetrics)
        self.line_18.setGeometry(QtCore.QRect(20, 240, 471, 16))
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.label_10 = QtGui.QLabel(SpatialMetrics)
        self.label_10.setGeometry(QtCore.QRect(310, 260, 171, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.progressBar_2 = QtGui.QProgressBar(SpatialMetrics)
        self.progressBar_2.setGeometry(QtCore.QRect(20, 360, 471, 21))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.pushButton_5 = QtGui.QPushButton(SpatialMetrics)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 310, 111, 31))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.txtBaseDir2_5 = QtGui.QLineEdit(SpatialMetrics)
        self.txtBaseDir2_5.setGeometry(QtCore.QRect(150, 20, 291, 31))
        self.txtBaseDir2_5.setObjectName(_fromUtf8("txtBaseDir2_5"))
        self.label_16 = QtGui.QLabel(SpatialMetrics)
        self.label_16.setGeometry(QtCore.QRect(20, 130, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setTextFormat(QtCore.Qt.AutoText)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.line_2 = QtGui.QFrame(SpatialMetrics)
        self.line_2.setGeometry(QtCore.QRect(20, 270, 471, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_7 = QtGui.QLabel(SpatialMetrics)
        self.label_7.setGeometry(QtCore.QRect(90, 260, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))

        self.retranslateUi(SpatialMetrics)
        QtCore.QMetaObject.connectSlotsByName(SpatialMetrics)

    def retranslateUi(self, SpatialMetrics):
        SpatialMetrics.setWindowTitle(QtGui.QApplication.translate("SpatialMetrics", "Spatial indicators for ES", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBaseDir_3.setToolTip(QtGui.QApplication.translate("SpatialMetrics", "Select a base directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("SpatialMetrics", "Indicator  visualisation Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("SpatialMetrics", "Select directory", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setToolTip(QtGui.QApplication.translate("SpatialMetrics", "Select an indicator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("SpatialMetrics", "Confirm spatial indicator :", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setToolTip(QtGui.QApplication.translate("SpatialMetrics", "Click to view graphs", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("SpatialMetrics", "  view", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBox.setToolTip(QtGui.QApplication.translate("SpatialMetrics", "Click to confirm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setToolTip(QtGui.QApplication.translate("SpatialMetrics", "Select ES to evaluate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("SpatialMetrics", "Ecosystem services", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("SpatialMetrics", "Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setToolTip(QtGui.QApplication.translate("SpatialMetrics", "Click to view maps", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("SpatialMetrics", "Open ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("SpatialMetrics", "Spatial indicators", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("SpatialMetrics", "Maps", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
